Tron2Cfg:
  robot_variant: SF_TRON2A
  xml_path: robot-description/SF_TRON2A/xml/robot.xml

  init_state:
    joint_names:
      - "proximal_pitch_L_Joint"
      - "proximal_roll_L_Joint"
      - "proximal_yaw_L_Joint"
      - "knee_L_Joint"
      - "ankle_pitch_L_Joint"
      - "proximal_pitch_R_Joint"
      - "proximal_roll_R_Joint"
      - "proximal_yaw_R_Joint"
      - "knee_R_Joint"
      - "ankle_pitch_R_Joint"
    default_joint_angle:
      proximal_pitch_L_Joint: 0.0
      proximal_roll_L_Joint: 0.0
      proximal_yaw_L_Joint: -3.1415
      knee_L_Joint: 0.0
      ankle_pitch_L_Joint: 0.0
      proximal_pitch_R_Joint: 0.0
      proximal_roll_R_Joint: 0.0
      proximal_yaw_R_Joint: 3.1415
      knee_R_Joint: 0.0
      ankle_pitch_R_Joint: 0.0

  control:
    joint_control_modes:
      - "position"
      - "position"
      - "position"
      - "position"
      - "position"
      - "position"
      - "position"
      - "position"
      - "position"
      - "position"

    leg_joint_stiffness: 159.67
    leg_joint_damping: 10.16
    light_joint_stiffness: 53.22
    light_joint_damping: 3.39
    action_scale_pos: 0.25
    action_scale_vel: 1.0
    decimation: 10

    leg_joint_torque_limit: 140.0
    light_joint_torque_limit: 40.0

  normalization:
    clip_scales:
      clip_observations: 100.0
      clip_actions: 100.0

  size:
    actions_size: 10
    policy_obs_size: 42
    commands_obs_size: 3
    encoder_input_size: 420
    encoder_output_size: 3
    policy_input_size: 48
    obs_history_length: 10

  commands:
    max:
      lin_vel_x: 1.0
      lin_vel_y: 1.0
      ang_vel_yaw: 1.0

  gait:
    enabled: true
    frequency: 0.8
    offset: 0.5
    duration: 0.5
    swing_height: 0.2

  stand_mode:
    stand_duration: 1.0

  imu_orientation_offset:
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
