joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

tron2_controller:
  type: tron2_controller/WheelfootController
  imu_name: base_imu
  hw_control_dt: 0.001
